[Visual_Studio]
url='https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&channel=Release&version=VS2022&source=VSLandingPage&cid=2030:8e0a127f6b34482599782b1911928b9f'

[VSCode]
url='https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user'

[Jetbrains_Studio]
url='https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.4.2.32922.exe'

[Steam]
url='https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe'

[FireFox]
url='https://download.mozilla.org/?product=firefox-stub&os=win&lang=en-US'

[XIVLauncher]
url='https://github.com/goatcorp/FFXIVQuickLauncher/releases/latest/download/Setup.exe'

[Discord]
url='https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x64'

[Malwarebytes]
url='https://downloads.malwarebytes.com/file/mb-windows'

[Eagle]
url='https://r2-app.eagle.cool/releases/Eagle-4.0-x64-build2.exe'

[Obsidian]
url='https://github.com/obsidianmd/obsidian-releases/releases/latest/download/Obsidian-1.6.7.exe'

[Bitwarden]
url='https://vault.bitwarden.com/download/?app=desktop&platform=windows'

[qbittorrent]
url='https://www.fosshub.com/qBittorrent.html?dwl=qbittorrent_4.6.6_x64_setup.exe'

[NVIDIA_Broadcast]
url='https://international.download.nvidia.com/Windows/broadcast/1.4.0.29/NVIDIA_Broadcast_v1.4.0.29.exe'

[Razer_Synapse]
url='https://rzr.to/synapse-new-pc-download-beta'

[7-Zip]
url='https://www.7-zip.org/a/7z2408-x64.exe'

[Rustup]
url='https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe'

[OBS_Studio]
url='https://cdn-fastly.obsproject.com/downloads/OBS-Studio-30.2.3-Windows-Installer.exe'

[OpenRGB]
url='https://gitlab.com/CalcProgrammer1/OpenRGB/-/jobs/artifacts/master/download?job=Windows%2064'
download_type="ZIP"
file_destination='C:\\Program Files\\'

[Ghidra]
url='https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.1.2_build/ghidra_11.1.2_PUBLIC_20240709.zip'
download_type="ZIP"
file_destination="C:\\ProgramFiles\\"
